### ISSUE TITLE
What is your experience/recommendation processing multiple productive rearrangements?

### ISSUE THREAD

**Issue by scharch** [BosingerLab/BALDR#9]
[N701_S502.IGH.filtered.txt](https://github.com/BosingerLab/BALDR/files/3497963/N701_S502.IGH.filtered.txt)
For instance, this is supposedly a single cell, but the various reconstructed heavy chains all have roughly the same number of reads in Bowtie. Six of them are VH3's --is it possible that Bowtime is allowing multimapping and that they are inflating each other's read counts? Any other tips for identifying the real one?

**Comment by amit-upadhyay** [comment]
BALDR runs bowtie for individual sequences. The rationale behind doing this was that if multiple sequences are included when running bowtie that are very similar, it randomly assigns reads to one sequence. To overcome this and get the actual number of reads that support a sequence, bowtie is run on individual sequences. In such cases where multiple assemblies have high read counts, I usually discard the cell.

**Comment by scharch** [comment]
That seems perfectly reasonable, I'm just wondering if you have a sense of
how often it accidentally make a bad assembly look like it has decent
support. I guess I'm asking how strict the bowtie settings are....
Thanks

**Comment by amit-upadhyay** [comment]
I have used --gbar 1000 --end-to-end so that it does not allow gapped alignment and aligns the entire read, but it is using the default scoring. I have not tried different scoring parameters for bowtie2 yet. 

In most cases, looking at the number of reads mapping to the entire sequence and the V(D)J gives a good idea of what would be the right assembly. But we do end up with such cases where its not clearly resolved. The frequency of ambiguous cases varies between datasets and also depends on the type of B cells. My guess would be between 10%-25%.
